version: '3'
services:
 frontend:
  build: ./frontend/
  ports:
     - 3000:3000
  depends_on:
      - database
 database:
  build: ./postgresDB
  ports:
     - 8080:8080
 backend: 
  build: ./backend/
  ports: 
     - 9000:9000
  depends_on:
      - database
 openid: 
  build: ./OIDC-provider/
  ports: 
     - 4000:4000
  depends_on:
      - frontend


